name: Setup
runs:
  using: composite
  steps:
    - name: Cache MariaDB
      id: cache-mariadb
      uses: actions/cache@v4
      with:
        key: mariadb-10.5.26-winx64
        path: C:\MariaDB
    - name: Setup MariaDB
      if: steps.cache-mariadb.outputs.cache-hit != 'true'
      shell: cmd
      run: |
        curl -sLO https://downloads.mariadb.org/rest-api/mariadb/10.5.26/mariadb-10.5.26-winx64.zip
        7z x -oC: -spe mariadb-10.5.26-winx64.zip
        C:\mariadb-10.5.26-winx64\bin\mariadb-install-db.exe
        start /b C:\mariadb-10.5.26-winx64\bin\mysqld.exe --port=3306
        C:\mariadb-10.5.26-winx64\bin\mysql.exe --port=3306 --user=root --password="" -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'Password12!'; FLUSH PRIVILEGES;"
        taskkill /f /im mysqld.exe
        ren C:\mariadb-10.5.26-winx64 MariaDB
    - name: Start MariaDB
      shell: cmd
      run: |
        start /b C:\MariaDB\bin\mysqld.exe --port=3306
    - name: Setup MSSQL
      shell: pwsh
      run: |
        choco install sql-server-express -y --no-progress --install-arguments="/SECURITYMODE=SQL /SAPWD=Password12!"
    - name: Setup PostgreSQL
      shell: pwsh
      run: |
        Set-Service -Name "postgresql-x64-14" -StartupType manual -Status Running
        pwsh -Command { $env:PGPASSWORD="root"; & "$env:PGBIN\psql" -U postgres -c "ALTER USER postgres WITH PASSWORD 'Password12!';" }
