name: Push
on:
  push:
    paths-ignore:
      - docs/*
      - NEWS
      - UPGRADING
      - UPGRADING.INTERNALS
      - README.md
      - CONTRIBUTING.md
      - CODING_STANDARDS.md
    branches:
      - PHP-7.4
      - PHP-8.0
      - PHP-8.1
      - master
      - cmb/gh-ci
  pull_request:
    branches:
      - '**'
jobs:
  # LINUX_X64:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       include:
  #         - debug: true
  #           zts: false
  #         - debug: false
  #           zts: true
  #   name: "LINUX_X64_${{ matrix.debug && 'DEBUG' || 'RELEASE' }}_${{ matrix.zts && 'ZTS' || 'NTS' }}"
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: git checkout
  #       uses: actions/checkout@v2
  #     - name: Create mssql container
  #       uses: ./.github/actions/mssql
  #     - name: apt
  #       uses: ./.github/actions/apt-x64
  #     - name: ./configure
  #       uses: ./.github/actions/configure-x64
  #       with:
  #         configurationParameters: >-
  #           --${{ matrix.debug && 'enable' || 'disable' }}-debug
  #           --${{ matrix.zts && 'enable' || 'disable' }}-zts
  #     - name: make
  #       run: make -j$(/usr/bin/nproc) >/dev/null
  #     - name: make install
  #       uses: ./.github/actions/install-linux
  #     - name: Setup
  #       uses: ./.github/actions/setup-x64
  #     - name: Test
  #       uses: ./.github/actions/test-linux
  #     - name: Test Tracing JIT
  #       uses: ./.github/actions/test-linux
  #       with:
  #         runTestsParameters: >-
  #           -d zend_extension=opcache.so
  #           -d opcache.enable_cli=1
  #           -d opcache.jit_buffer_size=16M
  #     - name: Verify generated files are up to date
  #       uses: ./.github/actions/verify-generated-files
  # MACOS_DEBUG_NTS:
  #   runs-on: macos-10.15
  #   steps:
  #     - name: git checkout
  #       uses: actions/checkout@v2
  #     - name: brew
  #       uses: ./.github/actions/brew
  #     - name: ./configure
  #       uses: ./.github/actions/configure-macos
  #       with:
  #         configurationParameters: --enable-debug --disable-zts
  #     - name: make
  #       run: |-
  #         export PATH="/usr/local/opt/bison/bin:$PATH"
  #         make -j$(sysctl -n hw.logicalcpu) >/dev/null
  #     - name: make install
  #       run: sudo make install
  #     - name: Test
  #       uses: ./.github/actions/test-macos
  #     - name: Test Tracing JIT
  #       uses: ./.github/actions/test-macos
  #       with:
  #         runTestsParameters: >-
  #           -d zend_extension=opcache.so
  #           -d opcache.enable_cli=1
  #           -d opcache.protect_memory=1
  #           -d opcache.jit_buffer_size=16M
  #     - name: Verify generated files are up to date
  #       uses: ./.github/actions/verify-generated-files
  WINDOWS:
    runs-on: windows-2019
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        zts: [false]
        opcache: [false, true]
    steps:
      - name: Keep line endings
        run: git config --global core.autocrlf false
      - name: git checkout
        uses: actions/checkout@v2
      - name: Checkout php-sdk
        uses: actions/checkout@v2
        with:
          repository: 'php/php-sdk-binary-tools'
          path: 'php-sdk'
      - name: Fetch dependencies
        uses: ./.github/actions/windows-task-runner
        with:
          task: phpsdk_deps.bat -s staging -u
          arch: ${{matrix.arch}}
      - name: buildconf
        uses: ./.github/actions/windows-task-runner
        with:
          task: buildconf.bat
          arch: ${{matrix.arch}}
      - name: configure
        uses: ./.github/actions/windows-task-runner
        with:
          task: configure.bat --enable-snapshot-build --disable-test-ini ${{matrix.zts && '--enable-zts' || '--disable-zts'}}
          arch: ${{matrix.arch}}
      - name: make
        uses: ./.github/actions/windows-task-runner
        with:
          task: nmake
          arch: ${{matrix.arch}}
      - name: test
        run: call php-sdk\phpsdk-vs16-${{matrix.arch}}.bat -t .github\scripts\test_task.bat --task-args ${{matrix.opcache && 1 || 0}}
      - name: Peek
        run: tree /a ..
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: C:/artifacts
